import { chromium } from 'playwright';
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1600, height: 1000 } });
await p.goto(`file://${process.cwd()}/index.html#1`, { waitUntil: 'networkidle' });
await p.waitForTimeout(1500);
const counterText = () => p.locator('#counter').innerText();
console.log('start:', await counterText());
// click dead center of the slide -> focuses the iframe
await p.mouse.click(800, 500);
await p.waitForTimeout(300);
await p.keyboard.press('ArrowRight');
await p.waitForTimeout(600);
console.log('after click+ArrowRight:', await counterText());
await p.keyboard.press('ArrowRight');
await p.waitForTimeout(600);
console.log('after second ArrowRight:', await counterText());
await p.keyboard.press('ArrowLeft');
await p.waitForTimeout(600);
console.log('after ArrowLeft:', await counterText());
await b.close();
